### ISSUE TITLE
rect가 불필요해보입니다.

### ISSUE THREAD

**Issue by zzinpan** [Quska45/IDB#3]
https://github.com/Quska45/IDB/blob/ca2992555bc284e087955f2757e09010e2e619dc/IDB.Object2D/IDB.Object2D.js#L20

선을 실제로 안그리는 것같아요.
사용하는 이유가 있나요?

**Comment by Quska45** [comment]
도형안에 이미지를 그리는 기능을 구현하기 위함입니다.
clip을 사용했던 이유와 연관되어 있는데 도형안에 이미지를 그리는 기능을 구현 하려고 하면 rect를 그리고 clip 해준 다음 이미지를 그려야 한다고 생각했습니다. 
개발 할 때 바로 이미지를 넣고 렌더링 해본거라 rect가 선을 그리는지 안그리는지도 딱히 생각해보지 않았습니다.
더 생각하고 꼼꼼하게 해보겠습니다.
